import type { PluginManifest } from '../../src/sdk/types';

const manifest: PluginManifest = {
  id: 'random-image',
  name: 'Random image',
  description: 'A slideshow from a folder on the Pi, your own URLs, or free photo/art providers by subject (Wikimedia, NASA, Cleveland Museum of Art, Unsplash, Pexels…).',
  version: '1.0.0',
  sdkVersion: 1,
  minHost: '0.1.0',
  author: 'MagicDash',
  icon: '🖼️',
  defaultSize: { w: 4, h: 3 },
  minSize: { w: 2, h: 2 },
  frameless: true,
  settings: [
    { key: 'unsplashKey', label: 'Unsplash API key', type: 'string', secret: true, help: 'Free at unsplash.com/developers (50 requests/hour is plenty).' },
    { key: 'pexelsKey', label: 'Pexels API key', type: 'string', secret: true, help: 'Free at pexels.com/api.' },
    { key: 'pixabayKey', label: 'Pixabay API key', type: 'string', secret: true, help: 'Free at pixabay.com/api/docs.' },
    {
      key: 'folder',
      label: 'Image folder on the server',
      type: 'string',
      placeholder: '/home/pi/Pictures',
      help: 'Absolute path. jpg / png / gif / webp / avif files are picked up (sub-folders included).',
    },
  ],
  widgetConfig: [
    {
      key: 'source',
      label: 'Source',
      type: 'select',
      default: 'picsum',
      options: [
        { label: 'Random photos (Lorem Picsum, no subject)', value: 'picsum', group: 'Free, no key' },
        { label: 'LoremFlickr — photos by keyword', value: 'loremflickr', group: 'Free, no key' },
        { label: 'Wikimedia Commons — by subject', value: 'wikimedia', group: 'Free, no key' },
        { label: 'NASA image library — by subject', value: 'nasa', group: 'Free, no key' },
        { label: 'Cleveland Museum of Art — artworks by subject', value: 'cleveland', group: 'Free, no key' },
        { label: 'Unsplash — by subject', value: 'unsplash', group: 'Free API key' },
        { label: 'Pexels — by subject', value: 'pexels', group: 'Free API key' },
        { label: 'Pixabay — by subject', value: 'pixabay', group: 'Free API key' },
        { label: 'Folder on the server', value: 'folder', group: 'Mine' },
        { label: 'List of image URLs', value: 'urls', group: 'Mine' },
      ],
    },
    {
      key: 'subject',
      label: 'Subject',
      type: 'string',
      placeholder: 'e.g. mountains, golden retriever, van gogh, nebula',
      showWhen: { key: 'source', oneOf: ['loremflickr', 'wikimedia', 'nasa', 'cleveland', 'unsplash', 'pexels', 'pixabay'] },
      help: 'What the pictures should be about. Leave empty for the provider’s default.',
    },
    { key: 'urls', label: 'Image URLs', type: 'list', itemLabel: 'URL', placeholder: 'https://…', showWhen: { key: 'source', equals: 'urls' } },
    { key: 'subfolder', label: 'Sub-folder filter', type: 'string', placeholder: 'e.g. holidays/2025', showWhen: { key: 'source', equals: 'folder' }, help: 'Only show images whose path contains this text.' },
    { key: 'intervalSec', label: 'Change every', type: 'number', min: 3, max: 86400, default: 60, unit: 'seconds' },
    { key: 'fit', label: 'Fit', type: 'select', default: 'cover', options: [{ label: 'Fill tile (crop)', value: 'cover' }, { label: 'Fit inside', value: 'contain' }] },
    { key: 'kenBurns', label: 'Slow zoom effect', type: 'boolean', default: true },
    { key: 'shuffle', label: 'Shuffle', type: 'boolean', default: true },
    { key: 'caption', label: 'Show file name', type: 'boolean', default: false },
  ],
};
export default manifest;
